name: pizding-kartocheck
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - pyyaml
  - tqdm
  - pytorch
  - torchaudio
  - torchvision
  - pip:
      - transformers
      - librosa
      - soundfile

